version: "3.6"

services:

    my-site:
        # restart: always
        # In this case, docker is not going to download that image.... as we are defining a build
        # This info is going to be used to TAG the image
        image: my-site-image:latest
        # build: .
        build:
            context: .
            args:
                REPOSITORY: https://github.com/muccidavide/html-css-boolando